name: Android Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8' # distutils hatasÄ± Ã§Ã¶zÃ¼ldÃ¼

    - name: Install Buildozer
      run: pip install buildozer

    - name: Install Cython
      run: pip install cython # Cython hatasÄ± Ã§Ã¶zÃ¼ldÃ¼

    # ğŸ›‘ NÄ°HAÄ° Ã‡Ã–ZÃœM: Lisans kontrolÃ¼nÃ¼ atla
    - name: Run Buildozer (No License Check)
      run: buildozer android debug --nolicense

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-build-apk
        path: bin/*.apk
